Organ
work-design/rails_org pull request #8
Opened 2020-09-09 03:23 UTC by quoyi

2020-09-09 03:23 UTC, quoyi commented
@qinmingyuan

2020-09-09 03:58 UTC, qinmingyuan commented
我觉得组织不应该轻易删除，而是调整为离开组织比较稳妥。
1.  只有组织的创建者  owned: true ， 可以删除；
2.  其他人只能离开组织，即删除 member.

2020-09-09 09:41 UTC, quoyi commented
> 我觉得组织不应该轻易删除，而是调整为离开组织比较稳妥。
> 
> 1. 只有组织的创建者  owned: true ， 可以删除；
> 2. 其他人只能离开组织，即删除 member.

1. 从管理平台的功能上面讲应该是要删除功能的，如果不想物理删除可以考虑”标记删除“，查询的时候显示并标识”已删除“比较妥当。
2. 离开功能是需要的，另外组织管理者 ”修改组织成员“ 就相当于删除 member。

2020-09-09 10:13 UTC, qinmingyuan commented
现在的代码逻辑是：组织内的任何一个人都有权限删除该组织，肯定有问题啊

2020-09-11 03:18 UTC, qinmingyuan requested changes

2020-09-11 03:18 UTC, qinmingyuan commented on app/views/org/board/organs/_form.html.erb
> +    <%= ef.file_field :logo, class: 'input is-small', label: { class: 'label is-small' } %>
如果是统一设置，没必要在这里改样式。

2024-10-21 14:51 UTC, qinmingyuan commented
@qinmingyuan

2024-10-21 14:51 UTC, closed without merging